# Generated by Django 4.0.2 on 2022-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographical_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geography',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='geography',
            name='continent',
            field=models.CharField(choices=[('asia', 'Asia'), ('africa', 'Africa'), ('europe', 'Europe'), ('north_america', 'North America'), ('south_america', 'South America'), ('australia', 'Australia'), ('antarctica', 'Antarctica')], default='europe', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geography',
            name='iso_3166_code',
            field=models.CharField(help_text='Code as defined by ISO 3166 standard.', max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='geography',
            name='nuts_code',
            field=models.CharField(help_text='Code as defined by NUTS standard.', max_length=16, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='geography',
            name='code',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='standard',
        ),
    ]
