# Generated by Django 4.0.2 on 2023-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographical_module', '0002_alter_geography_unique_together_geography_continent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='italian_province_code',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
